# Generated by Django 4.0 on 2022-07-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_manager',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
